NIAD-615: Encounter add text
nhsconnect/integration-adaptor-111 pull request #108
Opened 2020-10-06 07:34 UTC by Broom94

2020-10-06 10:07 UTC, dawidskainos requested changes

2020-10-06 10:07 UTC, dawidskainos commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java
> +    private void addEncounterType(POCDMT000002UK01Encounter encounterITK, Encounter encounter) {
I don't think we should populate encounter.type this way
It's a CodeableConcept and it should match the valueset. Let's leave it empty for now - until v2.1 guidance is not ready.

2020-10-07 05:47 UTC, dawidskainos approved these changes

2020-10-07 12:15 UTC, saddiqs1 approved these changes

2020-10-07 12:22 UTC, Broom94 commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/EncounterMapper.java
> +            narrative.setDivAsString(Arrays.asList(DIV_START, divString, DIV_END)
replaces with + optional

2020-10-07 12:38 UTC, merged