NIAD-616: order by as codeable concept
nhsconnect/integration-adaptor-111 pull request #109
Opened 2020-10-06 08:31 UTC by bartek-sarul

2020-10-06 12:08 UTC, Broom94 approved these changes

2020-10-08 05:12 UTC, dawidskainos commented
I think it is not enough to add OrderedBy:eventDate. We should also sort list entries by date - where possible.

2020-10-09 10:21 UTC, dawidskainos requested changes

2020-10-09 10:21 UTC, dawidskainos commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/comparator/ResourceComparator.java
> +        Date date = null;
Is the purpose of this variable to be always null? ;)

2020-10-09 10:21 UTC, dawidskainos commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ListMapper.java
> +        resourcesCreated.stream().sequential().collect(Collectors.toCollection(() -> resourcesCreatedOrderedList));
why are making a copy of the resourcesCreated list?

2020-10-09 10:21 UTC, dawidskainos commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/comparator/ResourceComparatorTest.java
> +public class ResourceComparatorTest {
It's ok to use Mockito here, however it looks to me like an overkill. You can very easily create resources and set necessary dates without using mocking tools.

2020-10-09 10:21 UTC, dawidskainos commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/comparator/ResourceComparatorTest.java
> +    public void shouldReturnNegativeOneForValidDates() {
All these tests check comparator functionality pretty well, however they're hard to understand without digging into the code.

What I'd do:

    @Test
    public void shouldReturnOneWhenFirstResourceIsLater() {
        ReferralRequest first = new ReferralRequest().setAuthoredOn(LATER_DATE);
        ReferralRequest second = new ReferralRequest().setAuthoredOn(EARLIER_DATE);

        assertThat(resourceComparator.compare(first, second)).isEqualTo(1);
    }

2020-10-13 09:10 UTC, saddiqs1 approved these changes

2020-10-13 09:10 UTC, Broom94 approved these changes

2020-10-13 09:15 UTC, merged