Niad 1643 change patient's gender mapper
nhsconnect/integration-adaptor-111 pull request #181
Opened 2021-07-29 11:15 UTC by ssokolowskisebastian

2021-07-29 14:33 UTC, mrogowska requested changes

2021-07-29 14:33 UTC, mrogowska commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/GenderMapperTest.java
> +
Unnecessary empty lines

2021-07-30 06:47 UTC, dawidskainos commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/GroupMapperTest.java
> +
should be removed

2021-07-30 08:08 UTC, ssokolowskisebastian commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/GenderMapperTest.java
> +
done

2021-07-30 08:08 UTC, ssokolowskisebastian commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/GroupMapperTest.java
> +
done

2021-08-04 12:02 UTC, mrogowska approved these changes

2021-08-04 12:11 UTC, merged