NIAD-1669 adapter informationRecipient mapping
nhsconnect/integration-adaptor-111 pull request #189
Opened 2021-08-06 09:13 UTC by ssokolowskisebastian

2021-08-10 13:24 UTC, mrogowska requested changes

2021-08-10 13:24 UTC, mrogowska commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HealthcareServiceMapper.java
> +            if (code.getCode() == PRCP) {
I would check if typeCode == PRCP in line 41 in `mapHealthcareService` method, before trying to map HealthcareService. From what I understand, if InformationRecipient has different typeCode, then we don't want to map it at all.

2021-08-10 13:24 UTC, mrogowska commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HealthcareServiceMapper.java
> +    private static final String PRCP = "PRCP";
More descriptive name would be nice, for example `PRCP _TYPE_CODE` or something similar.

2021-08-10 13:24 UTC, mrogowska commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HealthcareServiceMapper.java
> +        informationRecipient.getTypeCode();
Please remove this

2021-08-11 08:14 UTC, mrogowska requested changes

2021-08-11 08:14 UTC, mrogowska commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HealthcareServiceMapper.java
> +            if(recipient.getTypeCode().toString() == PRCP_TYPE_CODE) {
Please use `equals` instead of `==` when comparing strings in Java.

2021-08-11 08:14 UTC, mrogowska commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HealthcareServiceMapper.java
> +            Organization organization = organizationMapper.mapOrganization(informationRecipient);
Why only informationRecipient is passed here? The old method still should be used, just modified to accept additional argument and use it.

2021-08-12 11:49 UTC, mrogowska requested changes

2021-08-12 11:49 UTC, mrogowska commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/OrganizationMapper.java
> +            Coding code = new Coding();
You could join setting to new Coding() and in other `mapOrganization` method there's nicer way to get Organization name:
```suggestion
            Coding code = new Coding()
                .setCode(String.valueOf(informationRecipient.getTypeCode()))
             .setDisplay(nodeUtil.getNodeValueString(intendedRecipient.getReceivedOrganization().getNameArray(0)));
```
Then you'll also have to update the expectedResult.json.

2021-08-16 10:18 UTC, mrogowska requested changes
Integration tests are failing, please fix them.

2021-08-16 10:18 UTC, mrogowska commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/OrganizationMapper.java
> +                .setDisplay(nodeUtil.getAllText(intendedRecipient.getReceivedOrganization().getNameArray(0).getDomNode()));
I was thinking that nodeUtil.getNodeValueString method could be used here (like in the example in my previous comment): `.setDisplay(nodeUtil.getNodeValueString(intendedRecipient.getReceivedOrganization().getNameArray(0)));`

2021-08-16 10:18 UTC, mrogowska commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/LocationMapperTest.java
> +        when(organizationMapper.mapOrganization((POCDMT000002UK01Organization) any())).thenReturn(organization);
`any(POCDMT000002UK01Organization.class)`

2021-08-16 10:18 UTC, mrogowska commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/LocationMapperTest.java
> +        when(organizationMapper.mapOrganization((POCDMT000002UK01Organization) any())).thenReturn(organization);
`any(POCDMT000002UK01Organization.class)`

2021-08-16 13:47 UTC, dawidskainos requested changes
example message needs to be updated as well as the documentation

2021-08-16 13:47 UTC, dawidskainos commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/HealthcareServiceMapperTest.java
> +        lenient().when(informationRecipient.getTypeCode()).thenReturn(forString(PRCP_TYPE_CODE));
Why lenient? In this case it seems unnecessary. I'd avoid lenient mocking in general - unless we have a good reason.

2021-08-16 13:47 UTC, dawidskainos commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/OrganizationMapperTest.java
> +        lenient().when(informationRecipient.getTypeCode()).thenReturn(forString(PRCP_TYPE_CODE));
Why lenient? In this case it seems unnecessary. I'd avoid lenient mocking in general - unless we have a good reason.

2021-08-16 13:47 UTC, dawidskainos commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/OrganizationMapperTest.java
> +    @Mock
This seems to be unused

2021-08-16 13:47 UTC, dawidskainos commented on service/src/test/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/OrganizationMapperTest.java
> +        assertThat(organization.getType().get(0).getCoding().get(0).getCode()).isEqualTo(PRCP_TYPE_CODE);
Maybe we could use getTypeFirstRep() and getCodingFirstRep() methods instead of accessing items by index 0?

2021-08-18 07:21 UTC, mrogowska approved these changes

2021-08-18 07:28 UTC, dawidskainos approved these changes

2021-08-18 07:29 UTC, merged