Niad 2122 ambulance input
nhsconnect/integration-adaptor-111 pull request #255
Opened 2022-07-08 13:08 UTC by hodge70

2022-07-08 14:14 UTC, SRAlexander requested changes

2022-07-08 14:14 UTC, SRAlexander commented on test-suite/client/src/data/schema.ts
> +                  template: require("./ambulance-itk-request.xml"),
This needs to be added to the commit

2022-07-11 14:40 UTC, hodge70 commented on test-suite/client/src/data/schema.ts
> +                  template: require("./ambulance-itk-request.xml"),
Added idk file as discussed

2022-07-12 07:50 UTC, SRAlexander requested changes

2022-07-12 07:50 UTC, SRAlexander commented on test-suite/client/src/data/schema.ts
> +                        id: "recipient-name",
Does not appear in ITK message.

Could you update the ITK message with the missing field, other ITK messages should have the field within them... syntax should be along the lines of @@id@@.

2022-07-12 07:50 UTC, SRAlexander commented on test-suite/client/src/data/schema.ts
> +                        id: "recipient-street-address-line-1",
Does not appear in ITK message.

Could you update the ITK message with the missing field, other ITK messages should have the field within them... syntax should be along the lines of @@id@@.

2022-07-12 07:50 UTC, SRAlexander commented on test-suite/client/src/data/schema.ts
> +                        id: "recipient-street-address-line-2",
Does not appear in ITK message.

Could you update the ITK message with the missing field, other ITK messages should have the field within them... syntax should be along the lines of @@id@@.

2022-07-12 07:50 UTC, SRAlexander commented on test-suite/client/src/data/schema.ts
> +                        id: "recipient-street-address-postcode",
Does not appear in ITK message.

Could you update the ITK message with the missing field, other ITK messages should have the field within them... syntax should be along the lines of @@id@@.

2022-07-12 07:50 UTC, SRAlexander commented on test-suite/client/src/data/schema.ts
> +                        id: "recipient-street-address-line-2",
* Placed on wrong line, this is for the case below

2022-07-12 07:50 UTC, SRAlexander commented on test-suite/client/src/data/schema.ts
> +                        id: "recipient-street-address-city",
* Placed on wrong line, this is for the case below

2022-07-14 08:04 UTC, merged