NIAD-550: Remove the RelatesTo field from the xml error response from 111
nhsconnect/integration-adaptor-111 pull request #68
Opened 2020-08-18 14:44 UTC by saddiqs1

2020-08-19 09:02 UTC, bartek-sarul requested changes

2020-08-19 11:14 UTC, dawidr-kainos approved these changes

2020-08-19 14:30 UTC, saddiqs1 commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/controller/ReportController.java
> +                    messageId, trackingId);
Should be fixed in the updated commit

2020-08-20 08:12 UTC, dawidr-kainos approved these changes

2020-08-20 08:13 UTC, Broom94 approved these changes

2020-08-20 08:13 UTC, merged