Map ITK -> QuestionnaireResponse, Questionare
nhsconnect/integration-adaptor-111 pull request #78
Opened 2020-09-21 14:04 UTC by Broom94

Questionnaire, Questionnaire mappers complete with dateutil amendments. Two extra util helpers created structuredBodyutil and Pathwayutil. Bundle update to add question and questionnaires. Tests created and amended.

2020-09-24 07:49 UTC, dawidskainos requested changes
Questionnaire and QuestionnaireResponse resources are missing fullUrls and are not included in List resource.

2020-09-24 09:43 UTC, dawidskainos submitted a review, later dismissed

2020-09-24 15:39 UTC, dawidskainos approved these changes

2020-09-24 15:46 UTC, saddiqs1 commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/QuestionnaireMapper.java
> +            new ContactDetail().addTelecom(
lines 50-53 need indenting?

2020-09-24 15:46 UTC, saddiqs1 commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/QuestionnaireMapper.java
> +        String value = "";
`StringUtils.EMPTY` is preferred to `""`

2020-09-24 15:46 UTC, saddiqs1 commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/QuestionnaireMapper.java
> +        if (value.equals("")) {
`value.isBlank()` is preferable?

2020-09-24 15:46 UTC, saddiqs1 commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/util/StructuredBodyUtil.java
> +            && entry.getContentId().getRoot().equals("2.16.840.1.113883.2.1.3.2.4.18.16")
Extract string here into constant

2020-09-24 16:00 UTC, saddiqs1 commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/QuestionnaireResponseMapper.java
> +            item.setLinkId("N/A");
Few references of `N/A` throughout multiple files, maybe make into a constant somewhere?

2020-09-24 16:13 UTC, saddiqs1 approved these changes

2020-09-25 07:47 UTC, dawidskainos approved these changes

2020-09-25 07:47 UTC, merged