Condition missing elements add code removed asserter
nhsconnect/integration-adaptor-111 pull request #86
Opened 2020-09-25 13:59 UTC by Broom94

2020-09-25 14:57 UTC, bartek-sarul submitted a review, later dismissed

2020-09-28 06:31 UTC, dawidskainos requested changes

2020-09-28 06:31 UTC, dawidskainos commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ConditionMapper.java
> +            .setAssertedDate(assertedDate)
We should populate full CodeableConcept - system, code and display
See for detailed values: http://hl7.org/fhir/stu3/valueset-languages.html

2020-09-28 11:55 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/enums/Language.java
> +            .orElse(null);
[optional] A good modern practice is not to return null but Optional or just throw exception that value does not exist

2020-09-28 11:55 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/enums/MaritalStatus.java
> +            .orElse(null);
[optional] A good modern practice is not to return null but Optional or just throw exception that value does not exist

2020-09-28 11:58 UTC, bartek-sarul requested changes

2020-09-28 11:58 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ConditionMapper.java
> +                                    .setDisplay(language.getDisplay())
Each line below can throw NPE as `fromCode` can return null

2020-09-28 11:58 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PatientMapper.java
> +                                    .setDisplay(maritalStatus.getDisplay())
Each line below can throw NPE as fromCode can return null

2020-09-29 07:01 UTC, dawidskainos approved these changes

2020-09-29 07:48 UTC, bartek-sarul requested changes

2020-09-29 07:48 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ConditionMapper.java
> +                            if (!StringUtils.isBlank(language.get().getDisplay())) {
Don't use `language.get()`. You already have the optional unwrapped in `lang` variable.

2020-09-29 07:48 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/ConditionMapper.java
> +                        Optional<Language> language = Language.fromCode(component.getSection().getLanguageCode().getCode());
You can inline this into 
```
Language.fromCode(component.getSection().getLanguageCode().getCode())
    .ifPresent(language -> { ...
```

2020-09-29 07:48 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PatientMapper.java
> +                        Optional<MaritalStatus> maritalStatus = MaritalStatus.fromCode(itkPatient.getMaritalStatusCode().getCode());
The same comment as in `ConditionMapper`

2020-09-29 07:48 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/oneoneone/cda/report/mapper/PatientMapper.java
> +                            if (!StringUtils.isBlank(maritalStatus.get().getCode())) {
The same comment as in `ConditionMapper`

2020-09-29 10:03 UTC, bartek-sarul approved these changes

2020-09-29 10:07 UTC, dawidskainos approved these changes

2020-09-29 10:09 UTC, merged